version: "0.1"
services: 
  ms-rdbms:
    build: .
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "aBc123!@#"
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
    volumes:
      - ./:/test/
    