version: "3.8"
services:
  database_server:
    image: mcr.microsoft.com/mssql/server
    # image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abc123!@#"
      DB_NAME: "movies"
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
  web_server:
    # image: debian:10-slim
    build: ./webserver
    depends_on:
      - database_server
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./applicatie/:/applicatie/
      - ./mssql-setup:/mssql-setup/
    command: php -S 0.0.0.0:80 -t /applicatie/