version: "0.1"
services:
  ms-rdbms:
    image: mcr.microsoft.com/mssql/server
    # image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abc123!@#"
      DB_NAME: "movies"
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
