version: "0.1"
services:
  ms-rdbms:
    image: mcr.microsoft.com/mssql/server
    # image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "aBc123!@#"
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
    volumes:
      - ./db/:/db/
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & 
        sleep 10
        /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -l 30 -e -i /db/setup.sql
        sleep infinity