version: "3.8"
services:
  database_server:
    image: mcr.microsoft.com/mssql/server
    # image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abc123!@#"
      DB_NAME: "movies"
      DB_HOST: "host.docker.internal,1434"
    ports:
      - target: 1433
        published: 1434
        protocol: tcp
        mode: host
  web_server:
    build: ./webserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "abc123!@#"
      DB_NAME: "movies"
      DB_HOST: "host.docker.internal,1434"
    depends_on:
      - database_server
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - ./applicatie/:/applicatie/
      - ./mssql-setup:/mssql-setup/
    entrypoint: sh /mssql-setup/bootstrap.sh